### ISSUE TITLE
Please update the Nuget package 

### ISSUE THREAD

**Issue by amitchaudhary-zz** [robsonj/GrovePi#17]
The nuget package is not updated as per latest source code.

**Comment by DexterInd** [comment]
Sorry Amit, the nuget?

**Comment by robsonj** [comment]
I'll update it at some point this week

**Comment by amitchaudhary-zz** [comment]
Actually I download the source also however the Buzzer and Accelerator are not working. Any help?

**Comment by SocalSam** [comment]
This is an amazing piece of work!  But the latest version of Visual Studio 2015 Community, 
Version 14.0.23107.0 D14REL and Visual Studio Tools for Universal Windows App 14.0.2312100 D14OOB, 
is not working and the nuget is not loading at all.
But looking forward to using this with my Raspberry Pi!

**Comment by ghost** [comment]
Hi, I'm wondering if you are planning on continuing to maintain this nuget? Or further develop the code at DexterIndusties' version? It seems really useful from the bits I've been able to use, but most of my sensors are not supported (digital Temp/Humidity and PIR Motion Detector). Thanks for your work!

**Comment by SocalSam** [comment]
The Nuget package is still not installing in my VS2015 Community version

**Comment by robsonj** [comment]
nuget package has been recompiled with the release of VS2015.

v1.0.5 is available via nuget
