### ISSUE TITLE
NuGet package isn't compatible with Win10 IoT projects

### ISSUE THREAD

**Issue by robotdad** [robsonj/GrovePi#19]
I tried loading this into a vanilla IoT C# project and can't add this package as a reference. The error, which isn't very helpful, is:
GrovePi 1.0.5 is not compatible with UAP,Version=v10.0.

**Comment by pranavkm** [comment]
The binaries under lib need to under `uap10.0` TFM and not directly under lib.

```
\lib
   \uap10.0
      \GrovePi.dll
```

**Comment by dcaro** [comment]
where is the GrovePi.dll ? I'm not sure which one to select ?

**Comment by robsonj** [comment]
Corrected the package structure and published nuget release v1.0.6 which also includes the fix for issue #21
