### ISSUE TITLE
Temperature & Humidity Sensor measures strange Celcius value 

### ISSUE THREAD

**Issue by PerryVanDerMeeren** [robsonj/GrovePi#21]
Hi,
I just built my first Win10 IoT App on the Raspberry Pi 2 where I connected the Temperature and Humidity Sensor to Port7 and the LCD RGB Backlight Display to I2C-1. 
With the following lines of code I tried to display the temperature:
public MainPage()
        {
            this.InitializeComponent();
                      DeviceFactory.Build.RgbLcdDisplay().SetText(
DeviceFactory.Build.TemperatureAndHumiditySensor(Pin.DigitalPin7, Model.OnePointTwo).TemperatureInCelcius().ToString(CultureInfo.InvariantCulture)
).SetBacklightRgb(0, 255, 255);
       }
It displays a value of 5.805! My actual room temperature is 23C at the moment.
Is there anything I am doing wrong? I tried different Digital ports but nothing changed.
And how can I detect the humidity? When that is not implemented yet, how can I help to extend the functionality? I love to contribute.

Thank you for your help.
Perry

**Comment by johnkoot** [comment]
I have the same problem. It implements an function reading the analog port, instead an one-wire protocol. I hope they fix it soon. Otherwise I need to implement one by myself.

**Comment by benoitjadinon** [comment]
fixed, see #22
